on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
jobs:
  ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          ansible-galaxy install -r requirements.yml
      - name: Run playbook
        env:
          AWS_ACCESS_KEY_ID: "ASIA2HD7NEBMSO3WSQ7E"
          AWS_SECRET_ACCESS_KEY: "GYcu/1hDLrZp8COEzwbEcO3BST2sF2LNvYrgBiA9"
          AWS_SECURITY_TOKEN: "IQoJb3JpZ2luX2VjEPf//////////wEaCXVzLWVhc3QtMSJHMEUCIBqgUxpau/rx9kRuk22nAxDWgvkIYpN+uA69Dbn7Xxz9AiEAvhiwww7Sp+sbZPfDD/JTCqF7stoPsQIGAmFlMYM9ShgqkQMIwP//////////ARACGgw3MDI0OTQzNTE0NDkiDEL9Ykr8bf0xf6lNTyrlAm3QC6bqZWDvRMqo5cj02QgqdZ+4Q18oWx55Wv0taoER9wsQ+dLCAgu9O0yPsdRzR1G5n/69PO7SfLsj8FJcPYUFheFRE3RmVU66WsoS9L6amAQ3XUaZPZVdAZ3l9FoVHKdCr+oE4NqJMBIUrCnrottSLGMevlNuJYSrL1esSRoR1PfHpxSrNG8Lc4sblC3yqc7rPE4j9r/g8KrGSIhKdCBNVs+/gjY3tcDQMWpZ4cEa1f/xK4NiCovpot5grtkCYUaMRSxXS0LVB+W+iZzi/7pC0/2Rmzp0VsrQqkvbcmyy34s22e6CJFqT5cpXD1Pwd2B/sjXEYQZ6iJQWGPOis0CkdoxXIPgjmcETJIy8+nMNiN1JX0WuZ78oJtrOnfumCWZ6EJ7TAlHU0jSd3060n21TnSpjZtx8tZ9aNHuJy1VGaeevR6PPracCGxy8RKP7t/3rZ9EYfBe1TWqG3VyLCMy5dong1jDxqo6NBjqmAZmLvxRJ4eDv7QVFzBec31Kh1w/tGXh7QGsRzf7jzv/vD1w3PzQnLucmjF0n2LxoTYrqCy+6ZYtwSFCxvWh3/4x9ZYk0uB9WWIMI1lgBixgcPIMVnk3sx94n4eCTwNGCaSRRYbmoSO/eefQe5wrJmoTKUdXPsz0Ga85TGtvIu1IkPSlJdrkc3rhmnstSJJAJcPKuIh0i9jTTzaGhQVkJ5Uac8XXq9x0="
          AWS_REGION: "eu-central-1"
          BIGIP_USERNAME: "admin"
          BIGIP_PASSWORD: "Default12345!"
          AWS_BUCKET_NAME: "default-judmf-bigip-1arm"
          BIGIP_PORT: "8443"
        run: |
          ansible-playbook site.yml 
