on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
jobs:
  ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          ansible-galaxy install -r requirements.yml
      - name: Run playbook
        env:
          AWS_ACCESS_KEY_ID: "ASIA2HD7NEBM76DBKZGZ"
          AWS_SECRET_ACCESS_KEY: "iLvdNZaolhaj6EUL1nO3vl4uh9eHtldfO7amGJ9l"
          AWS_SECURITY_TOKEN: "IQoJb3JpZ2luX2VjEB0aCXVzLWVhc3QtMSJIMEYCIQDbM0A6q1K4b77k+Hpttos10YRbMwp8DLmqpczN9IC+jQIhAI3uEJiHuCTC61XX7ZI6EDAI5t2iIbDwtGFJhPxGB1IMKogDCFUQAhoMNzAyNDk0MzUxNDQ5IgzZH3iX174k1V6IJCsq5QL1ehQq79MifF7n4p82KdllMSDVz1kfhBjys3oO3o9oniSC4U5/z74Ng2sjgLqmH+DSSKuUFto7DSqVr02vw549tdpZ4I40dNOUjTwcaRHyOGY86dQ3fLhfc4rZmSnz7RKr4aCQnjwnEC8DwLn75BXa6OuK1pGBcSIgtEcET7UE+hu1D76rWBsZmE2LXHeU4AvcbTgcMyfYhJl+Hb5hrnycl8l826sN/+hrHGniE0WtASmqn3rBPyVyxBfS+hncy2MU1blaoWjhmqCup/YbdCoNyjD1NC+N0uhB7HzuEKsWuKFcUUHRpAIFEjygqNXFA3GP40UUtL0KwKl+d+k6+W+Gk+6DnD0UAF3Rgz4Cqjfh74cSxxecrOzDJuHpDsAy40TnuUVqeh3puptGxmruQZ8GP0LMXi0tJONIgmp1Tif6Wh71Ny2mBmo6pKVfnYQ4a2Y/7qg2Ew44ZpBXrxRxq6FAiZo/uK8wvqqciQY6pQGnAi4r7AV46HN4OP0uRbgjoeWjPgLdTVS+aZwYwh0Xm6pFpaPeoUh0JY+fsdgAL0wFBT/xvhlWf+IpBWQB8xCz4pxdyl4ITlqfQLFmOXp2ie3PeDbOB1ZBdDKVGxRKjLgSq2uK4Kgz4y0q+tIPW23vv9WUZ83ztGAoDHiCO3GPh8IIzwTAQd3lCY9n2zZDPZYdiD8USAiBN+4YFw9PFuWoKbJtvqs="
          AWS_REGION: "eu-central-1"
          BIGIP_USERNAME: "admin"
          BIGIP_PASSWORD: "Default12345!"
          AWS_BUCKET_NAME: "default-judmf-bigip-1arm"
          BIGIP_PORT: "8443"
        run: |
          ansible-playbook site.yml 
