on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
jobs:
  ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          ansible-galaxy install -r requirements.yml
      - name: Run playbook
        env:
          AWS_ACCESS_KEY_ID: "ASIA2HD7NEBMUWMY4QST"
          AWS_SECRET_ACCESS_KEY: "C556YvAzNddcdk0VwHWBtDs+96EbuKmj0ggmgA66"
          AWS_SECURITY_TOKEN: "IQoJb3JpZ2luX2VjEAoaCXVzLWVhc3QtMSJIMEYCIQCHVurY9T78Oe8N7bvAtJcgw9hnxFUZ+iy9lHak41sdZAIhAOo+tLYGOSnnp3aW7/yAZbavAKOPwqN3EjH4ueFD/hTCKpEDCNP//////////wEQAhoMNzAyNDk0MzUxNDQ5Igz5zfSlYlqrDB1LjeMq5QLKFtvNQa2XKg20KEuSOeJcybMJXwAsG0AEJPj+hA52HO3BkBI/GIudyGrc6ngWga5WG9ryQ7C/RmBhfsPiiluvHduOrDuHchNT/272ZGUzZrj0mEIsuy5jlKFYLBnluGMT5LLPAEjO7EbOGJE0Pk/PHci/sIkXuJDLybvywDOlNrLUO9H2YRsxhPH8AwLFb6vS2bcunVMhbuvtIyj0m3BzyrCYXvFvjHEFINt95Ae4fYnhqLxlR7eFOQYVc8MH4hNCEaU1RMMtSvwesFGaVThi0bbta6M40y+Qg3JyIZz0GdKHL1tkFpYJb9siqXLsihOGWIiR/Nq2gABpt1PIZeyHoVSbCpgPDGTZTxrg2nE/1yNKofYpkqp6FfjWktMtQyD20yEarRarFE5BFcS72tvEWNa9jEGdxnaQIvjTNactcxOQqRGgIV5S96ZxMcfEPN4M0HsrkQTHeTPDJrQa4ClaswHUstUw7r6SjQY6pQEIVvUf5uU0Z2itZv/4T6iBSmmOkfcZRldDs07W7I6eltkH+VHsLwWh/qlhiI0GY7wMNh4izmqvdmsUM0FmcoHur1NbD22DWGapSHQe70m3bAVO88OjftU2V9Iv4qTtTTLBhBomAoXaxRsexb4MR0rFoOHL7DUxbyIH+vkdCBfx2scGhQJ+vIiFQHHEH1kdaKQw3SVfQkXXkd7pDdG+VptoT3W54yg="
          AWS_REGION: "eu-central-1"
          BIGIP_USERNAME: "admin"
          BIGIP_PASSWORD: "Default12345!"
          AWS_BUCKET_NAME: "default-judmf-bigip-1arm"
          BIGIP_PORT: "8443"
        run: |
          ansible-playbook site.yml 
